# Generated by Django 5.1.2 on 2026-06-19 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('iata_code', models.CharField(blank=True, max_length=2, verbose_name='Код IATA')),
                ('icao_code', models.CharField(blank=True, max_length=3, verbose_name='Код ICAO')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Авиакомпания',
                'verbose_name_plural': 'Авиакомпании',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('iata_code', models.CharField(max_length=3, verbose_name='Код IATA')),
                ('icao_code', models.CharField(blank=True, max_length=4, verbose_name='Код ICAO')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='AirportResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('check_in_counter', 'Стойка регистрации'), ('gate', 'Выход на посадку'), ('stand', 'Место стоянки'), ('vehicle', 'Спецтехника')], max_length=20, verbose_name='Тип')),
                ('terminal', models.CharField(blank=True, max_length=10, verbose_name='Терминал')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('occupied', 'Занят'), ('maintenance', 'На обслуживании'), ('unavailable', 'Недоступен')], default='available', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ресурс аэропорта',
                'verbose_name_plural': 'Ресурсы аэропорта',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10, verbose_name='Регистрационный номер')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('capacity', models.IntegerField(verbose_name='Пассажировместимость')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='api.airline', verbose_name='Авиакомпания')),
            ],
            options={
                'verbose_name': 'Воздушное судно',
                'verbose_name_plural': 'Воздушные суда',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('entity', models.CharField(max_length=50, verbose_name='Сущность')),
                ('entity_id', models.IntegerField(verbose_name='ID сущности')),
                ('data', models.JSONField(default=dict, verbose_name='Данные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журналы аудита',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, verbose_name='Номер рейса')),
                ('scheduled_departure', models.DateTimeField(verbose_name='Плановое время вылета')),
                ('scheduled_arrival', models.DateTimeField(verbose_name='Плановое время прибытия')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время вылета')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время прибытия')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('check_in', 'Регистрация открыта'), ('boarding', 'Посадка'), ('departed', 'Вылетел'), ('arrived', 'Прибыл'), ('delayed', 'Задержан'), ('cancelled', 'Отменён'), ('waiting_for_resource', 'Ожидает назначения ресурсов')], default='scheduled', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='api.aircraft', verbose_name='Воздушное судно')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.airline', verbose_name='Авиакомпания')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='api.airport', verbose_name='Аэропорт назначения')),
                ('check_in_counter', models.ForeignKey(blank=True, limit_choices_to={'type': 'check_in_counter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_as_counter', to='api.airportresource', verbose_name='Стойка регистрации')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='api.airport', verbose_name='Аэропорт отправления')),
                ('gate', models.ForeignKey(blank=True, limit_choices_to={'type': 'gate'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_as_gate', to='api.airportresource', verbose_name='Выход на посадку')),
                ('stand', models.ForeignKey(blank=True, limit_choices_to={'type': 'stand'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_as_stand', to='api.airportresource', verbose_name='Место стоянки')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['scheduled_departure'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('awaiting_approval', 'На согласовании'), ('completed', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('planned_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата завершения')),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата завершения')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.airportresource', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Заявка на обслуживание',
                'verbose_name_plural': 'Заявки на обслуживание',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Номер билета')),
                ('seat_number', models.CharField(blank=True, max_length=5, verbose_name='Номер места')),
                ('class_type', models.CharField(choices=[('economy', 'Эконом'), ('business', 'Бизнес'), ('first', 'Первый')], default='economy', max_length=10, verbose_name='Класс')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('booked', 'Забронирован'), ('checked_in', 'Зарегистрирован'), ('boarded', 'Посажен на борт'), ('used', 'Использован'), ('cancelled', 'Отменён')], default='booked', max_length=20, verbose_name='Статус')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('payment_data', models.JSONField(default=dict, verbose_name='Данные о платеже')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.flight', verbose_name='Рейс')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
